### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by ozbillwang** [CenturyLinkLabs/dockerfile-from-image#7]
@bdehamer  

This is my own to-do list, if you think that's good idea, then I will work on them. Or you can help directly, let me know.
1. Add the function if the test image is not exist, pull it directly
2. Remove the useless space from output. For example: 

```
RUN apt-get update && apt-get install -y --no-install-recommends        bzr         git         mercurial       openssh-client      subversion  && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y --no-install-recommends        autoconf        automake        bzip2       file        g++         gcc         imagemagick         libbz2-dev      libc6-dev       libcurl4-openssl-dev        libevent-dev        libffi-dev      libglib2.0-dev      libjpeg-dev         liblzma-dev         libmagickcore-dev       libmagickwand-dev       libmysqlclient-dev      libncurses-dev      libpq-dev       libreadline-dev         libsqlite3-dev      libssl-dev      libtool         libwebp-dev         libxml2-dev         libxslt-dev         libyaml-dev         make        patch       xz-utils        zlib1g-dev  && rm -rf /var/lib/apt/lists/*
```

to

RUN apt-get update && apt-get install -y --no-install-recommends bzr git mercurial openssh-client subversion && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y --no-install-recommends autoconf automake bzip2 file g++ gcc imagemagick libbz2-dev libc6-dev libcurl4-openssl-dev libevent-dev libffi-dev libglib2.0-dev libjpeg-dev liblzma-dev libmagickcore-dev libmagickwand-dev libmysqlclient-dev libncurses-dev libpq-dev libreadline-dev libsqlite3-dev libssl-dev libtool libwebp-dev libxml2-dev libxslt-dev libyaml-dev make patch xz-utils zlib1g-dev && rm -rf /var/lib/apt/lists/*

**Comment by ozbillwang** [comment]
Seems your team has implemented with better solution (imagelayers.io),  I needn't spend time on it any more.

**Comment by ozbillwang** [comment]
idea 2 has been committed waiting for pull review by https://github.com/CenturyLinkLabs/dockerfile-from-image/pull/8 in commit ( b819707)

**Comment by ozbillwang** [comment]
for idea 1, i am thinking if we can get the command list without pull the image. 

@bdehamer I saw the website https://imagelayers.io/ and understand what it did. My curious is, the speed is so fast, looks the website didn't pull image and generate the command. 

Can you confirm?

**Comment by bdehamer** [comment]
@SydOps this project and imagelayers.io take two different approaches. The `dockerfile-from-image` tool was always intended to work against the local image cache (i.e. images that you've built locally or already pulled down from the hub). The idea was to keep it small and fast.

On the other hand, imagelayers.io was built specifically to inspect any public image on the Docker Hub. This requires significantly more work since we have to pull down the metadata for each layer in the image that you are inspecting. We're able to keep the performance reasonably fast through some aggressive caching of data. When you make a request to inspect an image, there's a good chance that someone else has already inspected that image (or at least some of the same layers that comprise that image). We derive a lot of efficiency from the fact that it's a hosted tool that a lot of people are using.

You certainly could do something similar with a command line tool like `dockerfile-from-image` but I sort of feel like that is beyond the scope of what this utility is trying to accomplish.

If that is something you are interested in, it may be a good opportunity to spin-up a separate project. There is probably some code that you could leverage from the imagelayers.io project to get you started.

**Comment by ozbillwang** [comment]
@bdehamer, Thanks for the explanation.
